Repository GoteoFoundation/goteo, pull requests merged in 2021-10, with the labels that each got.

#249 Fix Dropfiles to handle different types of documents (contracts and normal documents)
  src/Goteo/Util/Form/Type/DropfilesType.php
Labels: bug

#250 Fix image display width inside Project's Social Commitment Section
  public/assets/sass/project.scss
Labels: bug

#251 Feature/symfony upgrade to.3.4
  public/index.php
  src/Goteo/Application/EventListener/SessionListener.php
  src/Goteo/Util/Parsers/UrlLang.php
Labels: dev-edge

#252 Remove project's D3 end of round marker
  Resources/templates/responsive/project/partials/chart_amount.php
Labels: enhancement
