Repository GoteoFoundation/goteo, pull requests merged in 2021-09, with the labels that each got.

#221 Fix on deprectated parse_str function since PHP 7.2
  Resources/templates/default/partials/utils/paginator.php
Labels: bug

#229 Fix deprecated call of implode function
  Resources/templates/responsive/channel/call/partials/map.php
Labels: bug

#233 Fix call of implode that is deprecated since PHP72
  src/Goteo/Library/Check.php
Labels: bug

#234 Feature: Project can share a url to a signature platform
  Resources/templates/responsive/project/partials/main_extra.php
  Resources/templates/responsive/project/partials/responsive_meter.php
  Resources/translations/ca/overview.yml
  Resources/translations/en/overview.yml
  Resources/translations/es/overview.yml
  db/migrations/20210915125443_goteo_project_sign_url.php
  public/assets/sass/components/_buttons.scss
  public/assets/sass/project.scss
  src/Goteo/Library/Forms/Model/ProjectOverviewForm.php
  src/Goteo/Library/Forms/Model/ProjectTranslateOverviewForm.php
  src/Goteo/Model/Project.php
Labels: enhancement, dev-staging

#236 Make sign fields in project not mandatory
  src/Goteo/Library/Forms/Model/ProjectTranslateOverviewForm.php
Labels: bug

#240 Fix dropfiles type after symfony BC in 2.8.31
  Resources/templates/forms/bootstrap/dropfiles_widget.html.php
  composer.json
  composer.lock
  public/assets/js/forms.js
  src/Goteo/Controller/Admin/ChannelCriteriaAdminController.php
  src/Goteo/Library/Forms/AbstractFormProcessor.php
  src/Goteo/Library/Forms/Admin/AdminChannelResourceEditForm.php
  src/Goteo/Library/Forms/Admin/AdminFootprintEditForm.php
  src/Goteo/Library/Forms/Admin/AdminPostEditForm.php
  src/Goteo/Library/Forms/Admin/AdminProgramForm.php
  src/Goteo/Library/Forms/Admin/AdminSdgEditForm.php
  src/Goteo/Library/Forms/Admin/AdminSectionForm.php
  src/Goteo/Library/Forms/Admin/AdminSocialCommitmentEditForm.php
  src/Goteo/Library/Forms/Admin/AdminSphereEditForm.php
  src/Goteo/Library/Forms/Admin/AdminStoryEditForm.php
  src/Goteo/Library/Forms/Admin/AdminWorkshopEditForm.php
  src/Goteo/Library/Forms/Model/ProjectPostForm.php
  src/Goteo/Library/Forms/Model/ProjectStoryForm.php
  src/Goteo/Library/Forms/Model/ProjectTranslateOverviewForm.php
  src/Goteo/Library/Forms/Model/QuestionnaireCreateForm.php
  src/Goteo/Library/Forms/Model/QuestionnaireForm.php
  src/Goteo/Library/Forms/Model/UserProfileForm.php
  src/Goteo/Model/Node/NodeProgram.php
  src/Goteo/Model/Node/NodeResource.php
  src/Goteo/Model/Questionnaire/Answer.php
  src/Goteo/Model/Stories.php
  src/Goteo/Model/User.php
  src/Goteo/Model/Workshop.php
  src/Goteo/Util/Form/DataTransformer/UploadImageTransformer.php
  src/Goteo/Util/Form/Type/DropfilesType.php
  src/Goteo/Util/ModelNormalizer/Transformer/ChannelProgramTransformer.php
  src/Goteo/Util/ModelNormalizer/Transformer/ChannelResourceTransformer.php
Labels: bug, dev-staging

#237 Display cursor at current tab projects' button on homepage
  public/assets/sass/misc/_misc.scss
Labels: bug

#199 Fix dropfiles type after symfony BC in 2.8.31
  Resources/templates/forms/bootstrap/dropfiles_widget.html.php
  composer.json
  composer.lock
  public/assets/js/forms.js
  src/Goteo/Controller/Admin/ChannelCriteriaAdminController.php
  src/Goteo/Library/Forms/AbstractFormProcessor.php
  src/Goteo/Library/Forms/Admin/AdminChannelResourceEditForm.php
  src/Goteo/Library/Forms/Admin/AdminFootprintEditForm.php
  src/Goteo/Library/Forms/Admin/AdminPostEditForm.php
  src/Goteo/Library/Forms/Admin/AdminProgramForm.php
  src/Goteo/Library/Forms/Admin/AdminSdgEditForm.php
  src/Goteo/Library/Forms/Admin/AdminSectionForm.php
  src/Goteo/Library/Forms/Admin/AdminSocialCommitmentEditForm.php
  src/Goteo/Library/Forms/Admin/AdminSphereEditForm.php
  src/Goteo/Library/Forms/Admin/AdminStoryEditForm.php
  src/Goteo/Library/Forms/Admin/AdminWorkshopEditForm.php
  src/Goteo/Library/Forms/Model/ProjectPostForm.php
  src/Goteo/Library/Forms/Model/ProjectStoryForm.php
  src/Goteo/Library/Forms/Model/ProjectTranslateOverviewForm.php
  src/Goteo/Library/Forms/Model/QuestionnaireCreateForm.php
  src/Goteo/Library/Forms/Model/QuestionnaireForm.php
  src/Goteo/Library/Forms/Model/UserProfileForm.php
  src/Goteo/Model/Node/NodeProgram.php
  src/Goteo/Model/Node/NodeResource.php
  src/Goteo/Model/Questionnaire/Answer.php
  src/Goteo/Model/Stories.php
  src/Goteo/Model/User.php
  src/Goteo/Model/Workshop.php
  src/Goteo/Util/Form/DataTransformer/UploadImageTransformer.php
  src/Goteo/Util/Form/Type/DropfilesType.php
  src/Goteo/Util/ModelNormalizer/Transformer/ChannelProgramTransformer.php
  src/Goteo/Util/ModelNormalizer/Transformer/ChannelResourceTransformer.php
Labels: bug, dev-staging

#242 Feature/symfony upgrade to.3.4
  Resources/templates/forms/bootstrap/dropfiles_widget.html.php
  Resources/templates/responsive/project/partials/main_extra.php
  Resources/templates/responsive/project/partials/responsive_meter.php
  Resources/translations/ca/overview.yml
  Resources/translations/en/overview.yml
  Resources/translations/es/overview.yml
  composer.json
  composer.lock
  db/migrations/20210915125443_goteo_project_sign_url.php
  phpunit.xml.dist
  public/assets/js/forms.js
  public/assets/sass/components/_buttons.scss
  public/assets/sass/misc/_misc.scss
  public/assets/sass/project.scss
  public/aws-sns.php
  rector.php
  src/Goteo/Controller/Admin/CategoriesAdminController.php
  src/Goteo/Library/Check.php
  src/Goteo/Library/Forms/AbstractFormProcessor.php
  src/Goteo/Library/Forms/Admin/AdminChannelResourceEditForm.php
  src/Goteo/Library/Forms/Admin/AdminFootprintEditForm.php
  src/Goteo/Library/Forms/Admin/AdminPostEditForm.php
  src/Goteo/Library/Forms/Admin/AdminProgramForm.php
  src/Goteo/Library/Forms/Admin/AdminSdgEditForm.php
  src/Goteo/Library/Forms/Admin/AdminSectionForm.php
  src/Goteo/Library/Forms/Admin/AdminSocialCommitmentEditForm.php
  src/Goteo/Library/Forms/Admin/AdminSphereEditForm.php
  src/Goteo/Library/Forms/Admin/AdminStoryEditForm.php
  src/Goteo/Library/Forms/Admin/AdminWorkshopEditForm.php
  src/Goteo/Library/Forms/Model/ProjectOverviewForm.php
  src/Goteo/Library/Forms/Model/ProjectPostForm.php
  src/Goteo/Library/Forms/Model/ProjectStoryForm.php
  src/Goteo/Library/Forms/Model/ProjectTranslateOverviewForm.php
  src/Goteo/Library/Forms/Model/QuestionnaireCreateForm.php
  src/Goteo/Library/Forms/Model/QuestionnaireForm.php
  src/Goteo/Library/Forms/Model/UserProfileForm.php
  src/Goteo/Model/Node/NodeProgram.php
  src/Goteo/Model/Node/NodeResource.php
  src/Goteo/Model/Project.php
  src/Goteo/Model/Questionnaire/Answer.php
  src/Goteo/Model/Stories.php
  src/Goteo/Model/User.php
  src/Goteo/Model/Workshop.php
  src/Goteo/Util/Form/DataTransformer/UploadImageTransformer.php
  src/Goteo/Util/Form/Type/DropfilesType.php
  src/Goteo/Util/ModelNormalizer/Transformer/ChannelProgramTransformer.php
  src/Goteo/Util/ModelNormalizer/Transformer/ChannelResourceTransformer.php
  tests/Goteo/Application/CurrencyTest.php
  tests/Goteo/Controller/Admin/LicensesSubControllerTest.php
  tests/Goteo/Model/ProjectTest.php
Labels: dev-edge

#239 [STAGING] Hide project signature fields
  Resources/templates/responsive/dashboard/project/overview.php
  Resources/translations/ca/overview.yml
  Resources/translations/en/overview.yml
  Resources/translations/es/overview.yml
  src/Goteo/Library/Forms/Model/ProjectOverviewForm.php
  tests/Goteo/Model/FaqTest.php
Labels: dev-staging

#238 Hide project signature fields
  Resources/templates/responsive/dashboard/project/overview.php
  Resources/translations/ca/overview.yml
  Resources/translations/en/overview.yml
  Resources/translations/es/overview.yml
  src/Goteo/Library/Forms/Model/ProjectOverviewForm.php
  tests/Goteo/Model/FaqTest.php
Labels: enhancement, dev-staging

#245 Feature/symfony upgrade to.3.4
  public/index.php
Labels: dev-alpha
