Repository GoteoFoundation/goteo, pull requests merged in 2021-11, with the labels that each got.

#261 Fix Project allow comments
  Resources/templates/responsive/project/updates_post.php
Labels: bug

#260 FIX/ Translations of project's collaborations
  src/Goteo/Controller/Dashboard/ProjectDashboardController.php
  src/Goteo/Controller/Dashboard/TranslateProjectDashboardController.php
Labels: bug

#258 Fix PHPMailer Exception inside Mail class
  src/Goteo/Model/Mail.php
Labels: bug

#265 fix duplicated import of TextType in ProjectOverviewForm
  src/Goteo/Library/Forms/Model/ProjectOverviewForm.php
Labels: bug

#269 Bug/fix console exception listener missing
  extend/goteo-dev/src/Goteodev/Console/Command/StatusInitCommand.php
  src/Goteo/Console/Command/AbstractCommand.php
  src/Goteo/Console/Command/TestCommand.php
  src/Goteo/Console/Console.php
  src/Goteo/Console/EventListener/ConsoleExceptionListener.php
  src/container.php
Labels: bug, dev-edge

#268 Added ConsoleExceptionListener as an EventSubscriber
  extend/goteo-dev/src/Goteodev/Console/Command/StatusInitCommand.php
  src/Goteo/Console/Command/AbstractCommand.php
  src/Goteo/Console/Command/TestCommand.php
  src/Goteo/Console/Console.php
  src/Goteo/Console/EventListener/ConsoleExceptionListener.php
  src/Goteo/Console/EventListener/ConsoleMailingListener.php
  src/container.php
Labels: bug

#271 fix duplicated import of TextType in ProjectTranslateOverviewForm
  src/Goteo/Library/Forms/Model/ProjectTranslateOverviewForm.php
Labels: bug

#272 Create Preview Project permission
  Resources/permissions.yml
  Resources/roles.yml
  src/Goteo/Model/Project.php
Labels: enhancement

#273 Fix Matcher Model adding missing imports
  src/Goteo/Model/Matcher.php
Labels: bug

#274 Fix check if Matcher has Questionnaires
  src/Goteo/Model/Matcher.php
Labels: bug

#279 Fix Project Story Form
  src/Goteo/Controller/Dashboard/ProjectDashboardController.php
  src/Goteo/Library/Forms/Model/ProjectStoryForm.php
Labels: bug

#276 Include HttpClient when creating Payment Gateway (it seems none was added)
  extend/goteo-dev/src/Goteodev/Payment/DummyPaymentMethod.php
  src/Goteo/Controller/Admin/AccountsSubController.php
  src/Goteo/Payment/Method/AbstractPaymentMethod.php
  src/Goteo/Payment/Method/CashPaymentMethod.php
  src/Goteo/Payment/Method/PoolPaymentMethod.php
Labels: bug

#295 Bug/fix omnipay refund request
  extend/goteo-dev/src/Goteodev/Payment/DummyPaymentMethod.php
  src/Goteo/Controller/Admin/AccountsSubController.php
  src/Goteo/Payment/Method/AbstractPaymentMethod.php
  src/Goteo/Payment/Method/CashPaymentMethod.php
  src/Goteo/Payment/Method/PoolPaymentMethod.php
Labels: dev-edge

#296 Revert "Include HttpClient when creating Payment Gateway (it seems no…
  extend/goteo-dev/src/Goteodev/Payment/DummyPaymentMethod.php
  src/Goteo/Controller/Admin/AccountsSubController.php
  src/Goteo/Payment/Method/AbstractPaymentMethod.php
  src/Goteo/Payment/Method/CashPaymentMethod.php
  src/Goteo/Payment/Method/PoolPaymentMethod.php
Labels: dev-edge

#266 Fix Profile user preferences form
  src/Goteo/Application/Session.php
  src/Goteo/Controller/Dashboard/SettingsDashboardController.php
  src/Goteo/Controller/DashboardController.php
  src/Goteo/Controller/UserController.php
  src/Goteo/Library/Forms/Model/UserPreferencesForm.php
  src/Goteo/Model/User.php
Labels: bug, dev-staging

#297 Fix typos and table formatting in docs
  README.md
  docker/README.md
Labels: enhancement
