Repository GoteoFoundation/goteo, pull requests merged in 2022-07, with the labels that each got.

#467 Add missing rel=nofollow attributes to user's profile external links
  Resources/templates/responsive/user/profile.php
Labels: bug

#388 Deprecate Paypal fields from Project and Contract
  Resources/templates/responsive/dashboard/project/campaign.php
  db/migrations/20220711130748_goteo_update_allow_paypal.php
  src/Goteo/Controller/Dashboard/ProjectDashboardController.php
  src/Goteo/Library/Forms/Model/ProjectCampaignForm.php
  src/Goteo/Model/Contract.php
  src/Goteo/Model/Project/Account.php
  src/Routes/dashboard_routes.php
  translations/ca/contract.yml
  translations/en/contract.yml
  translations/es/contract.yml
Labels: enhancement

#463 Enable pure Symfony controllers
  Resources/templates/responsive/layout.php
  composer.json
  composer.lock
  src/Goteo/Application/CustomRouter.php
  src/Goteo/Application/Templating/FoilEngine.php
  src/Goteo/Application/Templating/TwigEngine.php
  src/Goteo/Application/View.php
  src/Goteo/Controller/BaseSymfonyController.php
  src/Goteo/Core/DB.php
  src/container.php
  src/routes.php
  templates/base.html.twig
Labels: enhancement

#473 Remove NPM grunt-phplint dependency because is not used and has security issues
  Gruntfile.js
  docs/developers/ENVIRONMENT.md
  grunt/phplint.js
  package-lock.json
  package.json
Labels: enhancement, dependencies, javascript
