Repository GoteoFoundation/goteo, pull requests merged in 2022-01, with the labels that each got.

#325 Project's report fix on matcher's amounts
  Resources/templates/legacy/project/report.html.php
Labels: bug

#328 Fix Impact Discover fetch of projects in List Projects view
  Resources/templates/responsive/impact_discover/partials/project.php
  public/assets/sass/layouts/_impact_discover.scss
  src/Goteo/Controller/Api/ProjectsApiController.php
Labels: bug

#334 Migrate test Github action to MariaDB 10.2
  .github/workflows/test.yml
Labels: bug

#329 Implemented support for PeerTube videos on Project overview
  .jshintrc
  README.md
  Resources/templates/forms/bootstrap/media_widget.html.php
  Resources/templates/responsive/project/partials/media.php
  Resources/translations/ast/overview.yml
  Resources/translations/ca/overview.yml
  Resources/translations/en/overview.yml
  Resources/translations/es/overview.yml
  public/assets/js/forms.js
  src/Goteo/Model/Project/Media.php
Labels: javascript, php

#337 Updated PeerTube preview to conform with latest URL changes for plata…
  public/assets/js/forms.js
Labels: dev-edge

#336 Updated PeerTube preview to conform with latest URL changes for plata…
  public/assets/js/forms.js
Labels: bug
