Repository GoteoFoundation/goteo, pull requests merged in 2022-04, with the labels that each got.

#393 Add related URL query string on Not Found exception so we can try to …
  src/legacy_dispatcher.php
Labels: bug

#396 Upgrade to Symfony 4.2
  composer.json
  composer.lock
  src/Goteo/Console/Command/RoundCommand.php
  src/Goteo/Library/Forms/Model/ProjectCampaignForm.php
Labels: enhancement, php

#398 Add robots.txt
  public/robots.txt
Labels: enhancement

#399 Upgrade to Symfony 4.3
  composer.json
  composer.lock
  extend/custom-domains/src/CustomDomains/EventListener/DomainListener.php
  extend/goteo-bot/src/GoteoBot/Application/EventListener/BotControllerListener.php
  extend/goteo-dev/src/Goteodev/Application/EventListener/LiveReloadListener.php
  extend/goteo-dev/src/Goteodev/Application/EventListener/MockListener.php
  extend/goteo-dev/src/Goteodev/Profiler/EventListener/ProfilerListener.php
  extend/invest-return/src/Goteo/EventListener/InvestStatusChangerListener.php
  extend/private-zones/src/Goteo/Application/EventListener/BasicAuthListener.php
  src/Goteo/Application/EventListener/AclListener.php
  src/Goteo/Application/EventListener/AuthListener.php
  src/Goteo/Application/EventListener/DonateInvestListener.php
  src/Goteo/Application/EventListener/ExceptionListener.php
  src/Goteo/Application/EventListener/InvestListener.php
  src/Goteo/Application/EventListener/OriginListener.php
  src/Goteo/Application/EventListener/PoolInvestListener.php
  src/Goteo/Application/EventListener/ProjectChannelListener.php
  src/Goteo/Application/EventListener/SessionListener.php
Labels: enhancement, php

#411 Upgrade to Symfony 4.4
  composer.json
  composer.lock
  src/Goteo/Application/EventListener/ExceptionListener.php
  src/Goteo/Application/EventListener/SessionListener.php
  src/Goteo/Console/Command/CacheCommand.php
  src/Goteo/Console/Command/CertificateCommand.php
  src/Goteo/Console/Command/ChannelCommand.php
  src/Goteo/Console/Command/ContractCommand.php
  src/Goteo/Console/Command/CronCommand.php
  src/Goteo/Console/Command/DBVerifierCommand.php
  src/Goteo/Console/Command/LocationCommand.php
  src/Goteo/Console/Command/MailingCommand.php
  src/Goteo/Console/Command/OpenDataCommand.php
  src/Goteo/Console/Command/RefundCommand.php
  src/Goteo/Console/Command/SendmailCommand.php
  src/Goteo/Console/Command/ToolkitCommand.php
  src/Goteo/Console/Command/TranslationsCommand.php
  src/Goteo/Core/Helpers.php
  src/Goteo/Library/Forms/Admin/AdminPostEditForm.php
  src/Goteo/Library/Forms/Model/ProjectPostForm.php
  src/Goteo/Model/Communication.php
  src/Goteo/Model/Contract.php
  src/Goteo/Util/Form/DataTransformer/ModelContractDocumentTransformer.php
  src/Goteo/Util/Form/DataTransformer/ModelImageTransformer.php
  src/Goteo/Util/Form/Type/DropfilesType.php
Labels: enhancement
